//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignaciones
    {
        public int Id_Asignacion { get; set; }
        public int Id_Conductor { get; set; }
        public int Id_Bus { get; set; }
        public System.DateTime Fecha_Asignacion { get; set; }
        public string Turno { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Buses Buses1 { get; set; }
        public virtual Conductores Conductores { get; set; }
        public virtual Conductores Conductores1 { get; set; }
    }
}
