//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boletos
    {
        public string Id_Boleto { get; set; }
        public int Id_Viaje { get; set; }
        public int Id_Pasajero { get; set; }
        public string Id_Asiento { get; set; }
        public decimal Precio { get; set; }
        public System.DateTime Fecha_Compra { get; set; }
        public string Estado { get; set; }
    
        public virtual Asientos Asientos { get; set; }
        public virtual Asientos Asientos1 { get; set; }
        public virtual Pasajeros Pasajeros { get; set; }
        public virtual Pasajeros Pasajeros1 { get; set; }
        public virtual Viajes Viajes { get; set; }
        public virtual Viajes Viajes1 { get; set; }
    }
}
