//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimientos
    {
        public int Id_Mantenimiento { get; set; }
        public int Id_Bus { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public decimal Costo { get; set; }
        public string EmpresaResponsable { get; set; }
    
        public virtual Buses Buses { get; set; }
        public virtual Buses Buses1 { get; set; }
    }
}
