//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEFEntities2 : DbContext
    {
        public BDEFEntities2()
            : base("name=BDEFEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asientos> Asientos { get; set; }
        public virtual DbSet<Asignaciones> Asignaciones { get; set; }
        public virtual DbSet<Boletos> Boletos { get; set; }
        public virtual DbSet<Buses> Buses { get; set; }
        public virtual DbSet<Conductores> Conductores { get; set; }
        public virtual DbSet<Mantenimientos> Mantenimientos { get; set; }
        public virtual DbSet<Pasajeros> Pasajeros { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Viajes> Viajes { get; set; }
    }
}
