//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viajes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viajes()
        {
            this.Boletos = new HashSet<Boletos>();
            this.Boletos1 = new HashSet<Boletos>();
        }
    
        public int Id_Viaje { get; set; }
        public int Id_Bus { get; set; }
        public int Id_Conductor { get; set; }
        public int Id_Ruta { get; set; }
        public string Estado { get; set; }
        public Nullable<System.DateTime> Fecha_Salida { get; set; }
        public Nullable<System.DateTime> Fecha_LLegada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boletos> Boletos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boletos> Boletos1 { get; set; }
        public virtual Buses Buses { get; set; }
        public virtual Buses Buses1 { get; set; }
        public virtual Conductores Conductores { get; set; }
        public virtual Conductores Conductores1 { get; set; }
        public virtual Rutas Rutas { get; set; }
        public virtual Rutas Rutas1 { get; set; }
    }
}
